from PyQt6 import QtCore, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(395, 162)
        self.pbConvert = QtWidgets.QPushButton(parent=Dialog)
        self.pbConvert.setGeometry(QtCore.QRect(290, 80, 75, 23))
        self.pbConvert.setObjectName("pbConvert")
        self.lbConvert = QtWidgets.QLabel(parent=Dialog)
        self.lbConvert.setGeometry(QtCore.QRect(20, 10, 51, 20))
        self.lbConvert.setObjectName("lbConvert")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(140, 40, 120, 91))
        self.groupBox.setObjectName("groupBox")
        self.ToUS = QtWidgets.QRadioButton(parent=self.groupBox)
        self.ToUS.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.ToUS.setObjectName("ToUS")
        self.ToUK = QtWidgets.QRadioButton(parent=self.groupBox)
        self.ToUK.setGeometry(QtCore.QRect(20, 40, 82, 17))
        self.ToUK.setObjectName("ToUK")
        self.ToAUS = QtWidgets.QRadioButton(parent=self.groupBox)
        self.ToAUS.setGeometry(QtCore.QRect(20, 60, 82, 17))
        self.ToAUS.setObjectName("ToAUS")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 40, 120, 91))
        self.groupBox_2.setObjectName("groupBox_2")
        self.FromUS = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.FromUS.setGeometry(QtCore.QRect(20, 20, 82, 17))
        self.FromUS.setObjectName("FromUS")
        self.FromUK = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.FromUK.setGeometry(QtCore.QRect(20, 40, 82, 17))
        self.FromUK.setObjectName("FromUK")
        self.FromAUS = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.FromAUS.setGeometry(QtCore.QRect(20, 60, 82, 17))
        self.FromAUS.setObjectName("FromAUS")
        self.pbExit = QtWidgets.QPushButton(parent=Dialog)
        self.pbExit.setGeometry(QtCore.QRect(290, 110, 75, 23))
        self.pbExit.setObjectName("pbExit")
        self.Amount = QtWidgets.QLineEdit(parent=Dialog)
        self.Amount.setGeometry(QtCore.QRect(80, 10, 113, 20))
        self.Amount.setObjectName("Amount")
        self.lbResult = QtWidgets.QLabel(parent=Dialog)
        self.lbResult.setGeometry(QtCore.QRect(290, 30, 61, 16))
        self.lbResult.setObjectName("lbResult")
        self.lbTxtResult = QtWidgets.QLabel(parent=Dialog)
        self.lbTxtResult.setGeometry(QtCore.QRect(290, 50, 47, 13))
        self.lbTxtResult.setObjectName("lbTxtResult")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pbConvert.setText(_translate("Dialog", "Calcular"))
        self.lbConvert.setText(_translate("Dialog", "Convertir"))
        self.groupBox.setTitle(_translate("Dialog", "Destino"))
        self.ToUS.setText(_translate("Dialog", "US$"))
        self.ToUK.setText(_translate("Dialog", "UK£"))
        self.ToAUS.setText(_translate("Dialog", "AUS$"))
        self.groupBox_2.setTitle(_translate("Dialog", "Origen"))
        self.FromUS.setText(_translate("Dialog", "US$"))
        self.FromUK.setText(_translate("Dialog", "UK£"))
        self.FromAUS.setText(_translate("Dialog", "AUS$"))
        self.pbExit.setText(_translate("Dialog", "Salir"))
        self.Amount.setText(_translate("Dialog", "0"))
        self.lbResult.setText(_translate("Dialog", "Resultado"))
        self.lbTxtResult.setText(_translate("Dialog", "0"))
